[project]
name = "lstm-stock-prediction"
version = "0.1.0"
description = "LSTM model for stock open price prediction"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "pandas",
    "numpy",
    "torch",
    "scikit-learn",
    "matplotlib"
]
